apiVersion: v1
kind: Pod
metadata:
   name: {{ .Release.Name }}-post-install
   annotations:
       "helm.sh/hook": "post-install"
       "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  containers:
  - name: post-install-container
    image: busybox
    imagePullPolicy: Always
    command: ['sh', '-c', 'echo The post-install hook is running && sleep 10' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0