apiVersion: v1
kind: Secret
metadata:
  name: my-devops-password
  labels:
    app: python-time-service
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}