- name: Deploy web application
  block:
    - name: Deploy Docker Compose file
      template:
        src: docker-compose.yml.j2
        dest: /home/{{ ansible_user }}/docker-compose.yml
      tags: compose

    - name: Start application with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user }}
      tags: compose


- import_tasks: 0-wipe.yml
  when: web_app_full_wipe | default(false)
  tags: wipe