apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-services-ingress
spec:
  rules:
  - host: python-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: time-service
            port:
              number: 8000
  - host: kotlin-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kotlin-service
            port:
              number: 8080
