apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kotlin-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nai1ka/S25-core-course-labs.git
    targetRevision: lab13
    path: k8s/kotlin-time-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}