replicaCount: 6
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumeMounts:
  - name: kotlin-data
    mountPath: /app/data

persistence:
  size: 1Gi
  name: kotlin-data

podManagementPolicy: Parallel