name: Kotlin App

on:
  pull_request:
    paths:
      - 'app_kotlin/**'
      - '.github/workflows/app_kotlin.yml'

jobs:
  initial:
    name: Building, Testing and Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_kotlin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and Test with Gradle
        run: ./gradlew clean build

      - name: Run Gradle Tests
        run: ./gradlew test

      - name: Run Detekt Linter
        run: ./gradlew detekt

  security:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        with:
          args: --skip-unresolved ./app_kotlin
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [initial, security]
    defaults:
      run:
        working-directory: app_kotlin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: app_kotlin
          file: app_kotlin/Dockerfile
          push: true
          tags: nai1ka/time-service-kotlin:latest